FROM python:3.14.2-slim

# 設定工作目錄
WORKDIR /app

COPY requirements.txt .
# 升級 pip 並安裝套件
RUN python -m pip install  --no-cache-dir -U pip setuptools wheel && \
    python -m pip install --no-cache-dir -r requirements.txt

COPY task08_onenote_embed_etl/ ./task08_onenote_embed_etl/

CMD ["python", "-m", "task08_onenote_embed_etl.main"]
