FROM python:3.14.2-slim

# 設定工作目錄
WORKDIR /app

COPY requirements.txt .
# 升級 pip 並安裝套件
RUN python -m pip install  --no-cache-dir -U pip setuptools wheel && \
    python -m pip install --no-cache-dir -r requirements.txt

COPY task03_leetcode_ccClub_etl/ ./task03_leetcode_ccClub_etl/

CMD ["python", "-m", "task03_leetcode_ccClub_etl.main"]